services:
  mlflow:
    image: "ghcr.io/mlflow/mlflow:v2.16.2"
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlruns/mlflow.db
      --default-artifact-root file:/mlartifacts
    volumes:
      - ./mlruns:/mlruns
      - ./artifacts:/mlartifacts
    restart: unless-stopped

  api:
    build: .
    container_name: framerate_apidocke
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - mlflow

  frontend:
    image: nginx:stable-alpine
    container_name: framerate_frontend
    ports:
      - "8501:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api
